"""Strategy base class and registry for Vibe-Trading.

Three-layer strategy architecture:
1. TrendStrategy - Identifies market direction
2. PullbackStrategy - Identifies corrections against trend
3. EntryStrategy - Generates precise entry signals

Usage:
    from agent.backtest.strategies import StrategyRegistry, TrendStrategy

    registry = StrategyRegistry()
    strategy = registry.get("trend_ema_adx")
    signals = strategy.generate(df)
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)


class StrategyType(Enum):
    """Strategy classification by purpose."""

    TREND = "trend"
    PULLBACK = "pullback"
    ENTRY = "entry"


@dataclass
class StrategyMetadata:
    """Metadata for a strategy."""

    name: str
    type: StrategyType
    description: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    market: str = "all"  # crypto, equity, futures, all
    tags: List[str] = field(default_factory=list)


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""

    timestamp: pd.Timestamp
    direction: int  # 1 = long, -1 = short, 0 = neutral
    strength: float  # 0.0 to 1.0
    confidence: float  # 0.0 to 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base class for all strategies.

    Subclasses must implement:
    - _calculate() - Core indicator calculations
    - _generate_signals() - Signal generation from indicators
    """

    def __init__(
        self,
        name: str,
        strategy_type: StrategyType,
        parameters: Optional[Dict[str, Any]] = None,
    ):
        """Initialize strategy.

        Args:
            name: Strategy identifier
            strategy_type: Type of strategy
            parameters: Strategy-specific parameters
        """
        self.name = name
        self.strategy_type = strategy_type
        self.parameters = parameters or {}
        self._indicators: Dict[str, pd.Series] = {}

    @abstractmethod
    def _calculate(self, df: pd.DataFrame) -> Dict[str, pd.Series]:
        """Calculate strategy indicators.

        Args:
            df: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            Dictionary of indicator Series
        """
        pass

    @abstractmethod
    def _generate_signals(
        self, df: pd.DataFrame, indicators: Dict[str, pd.Series]
    ) -> pd.Series:
        """Generate signals from indicators.

        Args:
            df: OHLCV DataFrame
            indicators: Calculated indicators

        Returns:
            Series of signals (-1, 0, 1)
        """
        pass

    def validate(self, df: pd.DataFrame) -> Tuple[bool, Optional[str]]:
        """Validate input data.

        Args:
            df: OHLCV DataFrame

        Returns:
            (is_valid, error_message)
        """
        required_cols = ["open", "high", "low", "close"]
        missing = [c for c in required_cols if c not in df.columns]
        if missing:
            return False, f"Missing columns: {missing}"

        if len(df) < 20:
            return False, "Insufficient data (need at least 20 bars)"

        return True, None

    def calculate_indicators(self, df: pd.DataFrame) -> Dict[str, pd.Series]:
        """Calculate and cache indicators.

        Args:
            df: OHLCV DataFrame

        Returns:
            Dictionary of calculated indicators
        """
        valid, error = self.validate(df)
        if not valid:
            raise ValueError(f"Invalid data: {error}")

        self._indicators = self._calculate(df)
        return self._indicators

    def generate(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generate signals for the entire DataFrame.

        Args:
            df: OHLCV DataFrame

        Returns:
            DataFrame with signal column added
        """
        valid, error = self.validate(df)
        if not valid:
            raise ValueError(f"Invalid data: {error}")

        # Calculate indicators
        indicators = self._calculate(df)
        self._indicators = indicators

        # Generate signals
        signals = self._generate_signals(df, indicators)

        # Create result DataFrame
        result = df.copy()
        result["signal"] = signals
        result["signal_name"] = self.name

        # Add individual indicator columns
        for name, series in indicators.items():
            result[name] = series

        return result

    def get_metadata(self) -> StrategyMetadata:
        """Get strategy metadata."""
        return StrategyMetadata(
            name=self.name,
            type=self.strategy_type,
            description=self.__doc__ or "",
            parameters=self.parameters,
        )


class StrategyRegistry:
    """Registry for managing and accessing strategies."""

    _strategies: Dict[str, BaseStrategy] = {}

    @classmethod
    def register(cls, strategy: BaseStrategy) -> None:
        """Register a strategy.

        Args:
            strategy: Strategy instance to register
        """
        cls._strategies[strategy.name] = strategy
        logger.info(f"Registered strategy: {strategy.name}")

    @classmethod
    def get(cls, name: str) -> Optional[BaseStrategy]:
        """Get a registered strategy by name.

        Args:
            name: Strategy name

        Returns:
            Strategy instance or None
        """
        return cls._strategies.get(name)

    @classmethod
    def list_strategies(
        cls, strategy_type: Optional[StrategyType] = None
    ) -> List[str]:
        """List registered strategy names.

        Args:
            strategy_type: Filter by type (optional)

        Returns:
            List of strategy names
        """
        if strategy_type is None:
            return list(cls._strategies.keys())

        return [
            name
            for name, s in cls._strategies.items()
            if s.strategy_type == strategy_type
        ]

    @classmethod
    def list_by_market(cls, market: str) -> List[str]:
        """List strategies for a specific market.

        Args:
            market: Market type (crypto, equity, futures, all)

        Returns:
            List of strategy names
        """
        return [
            name
            for name, s in cls._strategies.items()
            if s.parameters.get("market", "all") in (market, "all")
        ]
