"""Strategy base class and registry for Vibe-Trading.

Three-layer strategy architecture:
1. TrendStrategy - Identifies market direction
2. PullbackStrategy - Identifies corrections against trend
3. EntryStrategy - Generates precise entry signals

Usage:
    from agent.backtest.strategies import StrategyRegistry, TrendStrategy

    registry = StrategyRegistry()
    strategy = registry.get("trend_ema_adx")
    signals = strategy.generate(df)
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)


class StrategyType(Enum):
    """Strategy classification by purpose."""

    TREND = "trend"
    PULLBACK = "pullback"
    ENTRY = "entry"


@dataclass
class StrategyMetadata:
    """Metadata for a strategy."""

    name: str
    type: StrategyType
    description: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    market: str = "all"  # crypto, equity, futures, all
    tags: List[str] = field(default_factory=list)
    timeframes: List[str] = field(default_factory=list)
    supported_markets: List[str] = field(default_factory=list)


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""

    timestamp: pd.Timestamp
    direction: int  # 1 = long, -1 = short, 0 = neutral
    strength: float  # 0.0 to 1.0
    confidence: float  # 0.0 to 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base class for all strategies.

    Subclasses must implement:
    - _calculate() - Core indicator calculations
    - _generate_signals() - Signal generation from indicators
    """

    def __init__(
        self,
        name: str,
        strategy_type: StrategyType,
        parameters: Optional[Dict[str, Any]] = None,
    ):
        """Initialize strategy.

        Args:
            name: Strategy identifier
            strategy_type: Type of strategy
            parameters: Strategy-specific parameters
        """
        self.name = name
        self.strategy_type = strategy_type
        self.parameters = parameters or {}
        self._indicators: Dict[str, pd.Series] = {}

    @abstractmethod
    def _calculate(self, df: pd.DataFrame) -> Dict[str, pd.Series]:
        """Calculate strategy indicators.

        Args:
            df: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            Dictionary of indicator Series
        """
        pass

    @abstractmethod
    def _generate_signals(
        self, df: pd.DataFrame, indicators: Dict[str, pd.Series]
    ) -> pd.Series:
        """Generate signals from indicators.

        Args:
            df: OHLCV DataFrame
            indicators: Calculated indicators

        Returns:
            Series of signals (-1, 0, 1)
        """
        pass

    def validate(self, df: pd.DataFrame) -> Tuple[bool, Optional[str]]:
        """Validate input data.

        Args:
            df: OHLCV DataFrame

        Returns:
            (is_valid, error_message)
        """
        required_cols = ["open", "high", "low", "close"]
        missing = [c for c in required_cols if c not in df.columns]
        if missing:
            return False, f"Missing columns: {missing}"

        if len(df) < 20:
            return False, "Insufficient data (need at least 20 bars)"

        return True, None

    def calculate_indicators(self, df: pd.DataFrame) -> Dict[str, pd.Series]:
        """Calculate and cache indicators.

        Args:
            df: OHLCV DataFrame

        Returns:
            Dictionary of calculated indicators
        """
        valid, error = self.validate(df)
        if not valid:
            raise ValueError(f"Invalid data: {error}")

        self._indicators = self._calculate(df)
        return self._indicators

    def generate(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generate signals for the entire DataFrame.

        Args:
            df: OHLCV DataFrame

        Returns:
            DataFrame with signal column added
        """
        valid, error = self.validate(df)
        if not valid:
            raise ValueError(f"Invalid data: {error}")

        # Calculate indicators
        indicators = self._calculate(df)
        self._indicators = indicators

        # Generate signals
        signals = self._generate_signals(df, indicators)

        # Create result DataFrame
        result = df.copy()
        result["signal"] = signals
        result["signal_name"] = self.name

        # Add individual indicator columns
        for name, series in indicators.items():
            result[name] = series

        return result

    def get_metadata(self) -> StrategyMetadata:
        """Get strategy metadata."""
        return StrategyMetadata(
            name=self.name,
            type=self.strategy_type,
            description=self.__doc__ or "",
            parameters=self.parameters,
            tags=getattr(self, 'tags', []),
            timeframes=getattr(self, 'timeframes', []),
            supported_markets=getattr(self, 'supported_markets', []),
        )


class StrategyRegistry:
    """Registry for managing and accessing strategies."""

    _strategies: Dict[str, BaseStrategy] = {}

    @classmethod
    def register(cls, strategy: BaseStrategy) -> None:
        """Register a strategy.

        Args:
            strategy: Strategy instance to register
        """
        cls._strategies[strategy.name] = strategy
        logger.info(f"Registered strategy: {strategy.name}")

    @classmethod
    def get(cls, name: str) -> Optional[BaseStrategy]:
        """Get a registered strategy by name.

        Args:
            name: Strategy name

        Returns:
            Strategy instance or None
        """
        return cls._strategies.get(name)

    @classmethod
    def list_strategies(
        cls, strategy_type: Optional[StrategyType] = None
    ) -> List[str]:
        """List registered strategy names.

        Args:
            strategy_type: Filter by type (optional)

        Returns:
            List of strategy names
        """
        if strategy_type is None:
            return list(cls._strategies.keys())

        return [
            name
            for name, s in cls._strategies.items()
            if s.strategy_type == strategy_type
        ]

    @classmethod
    def list_by_market(cls, market: str) -> List[str]:
        """List strategies for a specific market.

        Args:
            market: Market type (crypto, equity, futures, all)

        Returns:
            List of strategy names
        """
        return [
            name
            for name, s in cls._strategies.items()
            if s.parameters.get("market", "all") in (market, "all")
        ]

    @classmethod
    def list_by_tags(cls, tags: List[str], match_all: bool = False) -> List[str]:
        """List strategies matching specified tags.

        Args:
            tags: List of tags to filter by
            match_all: If True, strategy must have ALL tags. If False, ANY tag.

        Returns:
            List of strategy names matching the tags
        """
        results = []
        for name, s in cls._strategies.items():
            strategy_tags = getattr(s, 'tags', [])
            if match_all:
                if all(tag in strategy_tags for tag in tags):
                    results.append(name)
            else:
                if any(tag in strategy_tags for tag in tags):
                    results.append(name)
        return results

    @classmethod
    def list_by_timeframe(cls, timeframe: str) -> List[str]:
        """List strategies supporting a specific timeframe.

        Args:
            timeframe: Timeframe string (e.g., '1d', '4h', '1h')

        Returns:
            List of strategy names supporting the timeframe
        """
        return [
            name
            for name, s in cls._strategies.items()
            if timeframe in getattr(s, 'timeframes', [])
        ]

    @classmethod
    def filter(
        cls,
        strategy_type: Optional[StrategyType] = None,
        tags: Optional[List[str]] = None,
        timeframe: Optional[str] = None,
        market: Optional[str] = None,
    ) -> List[str]:
        """Filter strategies by multiple criteria.

        Args:
            strategy_type: Filter by type
            tags: Filter by tags (must match ALL tags)
            timeframe: Filter by timeframe
            market: Filter by market

        Returns:
            List of strategy names matching all criteria
        """
        results = list(cls._strategies.keys())

        # Filter by type
        if strategy_type is not None:
            results = [n for n in results if cls._strategies[n].strategy_type == strategy_type]

        # Filter by tags
        if tags:
            results = [
                n for n in results
                if all(tag in getattr(cls._strategies[n], 'tags', []) for tag in tags)
            ]

        # Filter by timeframe
        if timeframe:
            results = [
                n for n in results
                if timeframe in getattr(cls._strategies[n], 'timeframes', [])
            ]

        # Filter by market
        if market:
            results = [
                n for n in results
                if market in getattr(cls._strategies[n], 'supported_markets', [])
                or 'all' in getattr(cls._strategies[n], 'supported_markets', [])
            ]
        return results

    @classmethod
    def get_metadata(cls, name: str) -> Optional[StrategyMetadata]:
        """Get metadata for a strategy.

        Args:
            name: Strategy name

        Returns:
            StrategyMetadata or None
        """
        strategy = cls._strategies.get(name)
        if strategy:
            return strategy.get_metadata()
        return None

    @classmethod
    def get_all_metadata(cls) -> Dict[str, StrategyMetadata]:
        """Get metadata for all strategies.

        Returns:
            Dictionary of name -> StrategyMetadata
        """
        return {name: s.get_metadata() for name, s in cls._strategies.items()}


# Import composer for convenience
from .composer import StrategyComposer, ComposerState, CompositeSignal
from .mtf import MTFAligner, MTFComposer, MTFConfig, Timeframe, AlignmentResult
