"""Strategy Composer - Automatically chains Trend + Pullback + Entry strategies.

The composer implements the three-layer confirmation architecture:
1. Trend Layer - Identifies market direction (W1/D1/H4)
2. Pullback Layer - Identifies corrections against trend
3. Entry Layer - Generates precise entry signals

This ensures:
- Only trade in the direction of the trend
- Wait for pullbacks to get better prices
- Confirm entries with volume/breakout signals

Usage:
    from agent.backtest.strategies.composer import StrategyComposer

    composer = StrategyComposer()
    composer.set_trend('trend_ema_adx')
    composer.set_pullback('pullback_rsi')
    composer.set_entry('entry_breakout')

    result = composer.generate(df_trend, df_pullback, df_entry)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Optional, Tuple

import pandas as pd

from . import BaseStrategy, StrategyType, StrategyRegistry, StrategySignal


class ComposerState(Enum):
    """State of the strategy composer."""
    NEUTRAL = "neutral"
    TREND_CONFIRMED = "trend_confirmed"
    PULLBACK_DETECTED = "pullback_detected"
    SIGNAL_TRIGGERED = "signal_triggered"


@dataclass
class CompositeSignal:
    """Signal generated by the strategy composer."""
    timestamp: pd.Timestamp
    direction: int  # 1 = long, -1 = short, 0 = neutral
    state: ComposerState
    trend_direction: int
    pullback_confirmed: bool
    entry_price: Optional[float]
    stop_loss: Optional[float]
    take_profit: Optional[float]
    confidence: float  # 0.0 to 1.0
    metadata: Dict


class StrategyComposer:
    """Chains multiple strategies for multi-layer confirmation.

    The composer follows this logic:
    1. Check trend direction (must be confirmed before proceeding)
    2. Wait for pullback (better entry price)
    3. Generate entry signal when all conditions met

    Example:
        >>> composer = StrategyComposer()
        >>> composer.set_trend('trend_ema_adx')
        >>> composer.set_pullback('pullback_rsi')
        >>> composer.set_entry('entry_breakout')
        >>>
        >>> # Run on different timeframes
        >>> trend_result = composer.run_trend(df_d1)
        >>> pullback_result = composer.run_pullback(df_h4)
        >>> entry_result = composer.run_entry(df_h1)
        >>>
        >>> # Get composite signal
        >>> signal = composer.get_composite_signal()
    """

    def __init__(
        self,
        trend_strategy: Optional[str] = None,
        pullback_strategy: Optional[str] = None,
        entry_strategy: Optional[str] = None,
    ):
        """Initialize the strategy composer.

        Args:
            trend_strategy: Name of trend strategy to use
            pullback_strategy: Name of pullback strategy to use
            entry_strategy: Name of entry strategy to use
        """
        self._trend_strategy: Optional[BaseStrategy] = None
        self._pullback_strategy: Optional[BaseStrategy] = None
        self._entry_strategy: Optional[BaseStrategy] = None

        # Cached results
        self._trend_result: Optional[pd.DataFrame] = None
        self._pullback_result: Optional[pd.DataFrame] = None
        self._entry_result: Optional[pd.DataFrame] = None

        # Current state
        self._state = ComposerState.NEUTRAL
        self._trend_direction: int = 0
        self._pullback_confirmed: bool = False
        self._last_signal: Optional[CompositeSignal] = None

        # Set strategies if provided
        if trend_strategy:
            self.set_trend(trend_strategy)
        if pullback_strategy:
            self.set_pullback(pullback_strategy)
        if entry_strategy:
            self.set_entry(entry_strategy)

    def set_trend(self, strategy_name: str) -> "StrategyComposer":
        """Set the trend strategy.

        Args:
            strategy_name: Name of registered trend strategy

        Returns:
            Self for chaining
        """
        strategy = StrategyRegistry.get(strategy_name)
        if strategy is None:
            raise ValueError(f"Strategy not found: {strategy_name}")
        if strategy.strategy_type != StrategyType.TREND:
            raise ValueError(f"Strategy {strategy_name} is not a TREND strategy")
        self._trend_strategy = strategy
        return self

    def set_pullback(self, strategy_name: str) -> "StrategyComposer":
        """Set the pullback strategy.

        Args:
            strategy_name: Name of registered pullback strategy

        Returns:
            Self for chaining
        """
        strategy = StrategyRegistry.get(strategy_name)
        if strategy is None:
            raise ValueError(f"Strategy not found: {strategy_name}")
        if strategy.strategy_type != StrategyType.PULLBACK:
            raise ValueError(f"Strategy {strategy_name} is not a PULLBACK strategy")
        self._pullback_strategy = strategy
        return self

    def set_entry(self, strategy_name: str) -> "StrategyComposer":
        """Set the entry strategy.

        Args:
            strategy_name: Name of registered entry strategy

        Returns:
            Self for chaining
        """
        strategy = StrategyRegistry.get(strategy_name)
        if strategy is None:
            raise ValueError(f"Strategy not found: {strategy_name}")
        if strategy.strategy_type != StrategyType.ENTRY:
            raise ValueError(f"Strategy {strategy_name} is not an ENTRY strategy")
        self._entry_strategy = strategy
        return self

    def run_trend(self, df: pd.DataFrame) -> pd.DataFrame:
        """Run trend strategy and cache result.

        Args:
            df: OHLCV DataFrame

        Returns:
            DataFrame with trend signals
        """
        if self._trend_strategy is None:
            raise ValueError("Trend strategy not set. Call set_trend() first.")
        self._trend_result = self._trend_strategy.generate(df)
        self._update_trend_state()
        return self._trend_result

    def run_pullback(
        self,
        df: pd.DataFrame,
        trend_direction: Optional[int] = None,
    ) -> pd.DataFrame:
        """Run pullback strategy and cache result.

        Args:
            df: OHLCV DataFrame
            trend_direction: If provided, only confirm pullbacks in this direction

        Returns:
            DataFrame with pullback signals
        """
        if self._pullback_strategy is None:
            raise ValueError("Pullback strategy not set. Call set_pullback() first.")
        self._pullback_result = self._pullback_strategy.generate(df)

        # Filter pullback signals by trend direction
        if trend_direction is not None and self._pullback_result is not None:
            # Only keep pullback signals that align with trend
            signal = self._pullback_result["signal"]
            aligned = (signal == trend_direction) | (signal == 0)
            self._pullback_result = self._pullback_result[aligned].copy()

        self._update_pullback_state()
        return self._pullback_result

    def run_entry(
        self,
        df: pd.DataFrame,
        min_confidence: float = 0.5,
    ) -> pd.DataFrame:
        """Run entry strategy and cache result.

        Args:
            df: OHLCV DataFrame
            min_confidence: Minimum confidence threshold

        Returns:
            DataFrame with entry signals
        """
        if self._entry_strategy is None:
            raise ValueError("Entry strategy not set. Call set_entry() first.")
        self._entry_result = self._entry_strategy.generate(df)

        # Filter by confidence if available
        if "confidence" in self._entry_result.columns:
            self._entry_result = self._entry_result[
                self._entry_result["confidence"] >= min_confidence
            ].copy()

        return self._entry_result

    def _update_trend_state(self) -> None:
        """Update internal state based on trend result."""
        if self._trend_result is None:
            self._state = ComposerState.NEUTRAL
            self._trend_direction = 0
            return

        last_signal = self._trend_result["signal"].iloc[-1]
        self._trend_direction = int(last_signal)

        if self._trend_direction != 0:
            self._state = ComposerState.TREND_CONFIRMED
        else:
            self._state = ComposerState.NEUTRAL

    def _update_pullback_state(self) -> None:
        """Update internal state based on pullback result."""
        if self._pullback_result is None:
            self._pullback_confirmed = False
            return

        # Check if there's a valid pullback signal aligned with trend
        if len(self._pullback_result) > 0:
            last_signal = self._pullback_result["signal"].iloc[-1]
            # Pullback confirmed if signal aligns with trend
            self._pullback_confirmed = last_signal == self._trend_direction
            if self._pullback_confirmed:
                self._state = ComposerState.PULLBACK_DETECTED

    def get_composite_signal(self) -> Optional[CompositeSignal]:
        """Get the composite signal based on all layers.

        Returns:
            CompositeSignal or None if no signal
        """
        if self._trend_result is None:
            return None

        last_time = self._trend_result.index[-1]
        close = self._trend_result["close"].iloc[-1]

        # Base signal from trend
        signal = CompositeSignal(
            timestamp=last_time,
            direction=self._trend_direction,
            state=self._state,
            trend_direction=self._trend_direction,
            pullback_confirmed=self._pullback_confirmed,
            entry_price=None,
            stop_loss=None,
            take_profit=None,
            confidence=0.5,
            metadata={
                "trend_signal": self._trend_result["signal"].iloc[-1]
                if self._trend_result is not None
                else 0,
                "pullback_confirmed": self._pullback_confirmed,
                "has_entry": self._entry_result is not None
                and len(self._entry_result) > 0,
            },
        )

        # Update confidence based on layer confirmations
        confidence = 0.3  # Base confidence from trend
        if self._trend_direction != 0:
            confidence += 0.2
        if self._pullback_confirmed:
            confidence += 0.3
        if self._entry_result is not None and len(self._entry_result) > 0:
            confidence += 0.2
            last_entry = self._entry_result.iloc[-1]
            signal.entry_price = close
            # Calculate stop loss based on ATR
            if "atr" in self._entry_result.columns:
                atr = self._entry_result["atr"].iloc[-1]
                if self._trend_direction == 1:  # Long
                    signal.stop_loss = close - 2 * atr
                    signal.take_profit = close + 3 * atr
                else:  # Short
                    signal.stop_loss = close + 2 * atr
                    signal.take_profit = close - 3 * atr

        signal.confidence = min(confidence, 1.0)
        self._last_signal = signal

        # Update state if entry triggered
        if signal.entry_price is not None:
            signal.state = ComposerState.SIGNAL_TRIGGERED

        return signal

    def generate(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generate composite signals from a single DataFrame.

        This is a convenience method that runs all strategies on the same data.

        Args:
            df: OHLCV DataFrame

        Returns:
            DataFrame with composite signals
        """
        if (
            self._trend_strategy is None
            or self._pullback_strategy is None
            or self._entry_strategy is None
        ):
            raise ValueError("All strategies must be set before calling generate()")

        # Run all strategies
        self.run_trend(df)
        self.run_pullback(df, trend_direction=self._trend_direction)
        self.run_entry(df)

        # Get composite signals
        signals = []
        for i in range(len(df)):
            ts = df.index[i]
            trend_dir = (
                self._trend_result["signal"].iloc[i]
                if self._trend_result is not None
                else 0
            )

            # Check pullback at this timestamp
            pullback_ok = False
            if self._pullback_result is not None and i < len(self._pullback_result):
                pullback_signal = self._pullback_result["signal"].iloc[i]
                pullback_ok = pullback_signal == trend_dir

            # Check entry at this timestamp
            entry_ok = False
            if self._entry_result is not None and i < len(self._entry_result):
                entry_signal = self._entry_result["signal"].iloc[i]
                entry_ok = entry_signal == trend_dir

            # Composite signal
            if entry_ok and pullback_ok and trend_dir != 0:
                composite_signal = trend_dir
                state = ComposerState.SIGNAL_TRIGGERED
            elif pullback_ok and trend_dir != 0:
                composite_signal = trend_dir
                state = ComposerState.PULLBACK_DETECTED
            elif trend_dir != 0:
                composite_signal = trend_dir
                state = ComposerState.TREND_CONFIRMED
            else:
                composite_signal = 0
                state = ComposerState.NEUTRAL

            signals.append(
                {
                    "timestamp": ts,
                    "signal": composite_signal,
                    "state": state.value,
                    "trend": trend_dir,
                    "pullback": pullback_ok,
                    "entry": entry_ok,
                }
            )

        result = pd.DataFrame(signals)
        result.set_index("timestamp", inplace=True)
        return result

    def get_available_strategies(self) -> Dict[str, List[str]]:
        """Get available strategies by type.

        Returns:
            Dictionary mapping type to list of strategy names
        """
        return {
            "trend": StrategyRegistry.list_strategies(StrategyType.TREND),
            "pullback": StrategyRegistry.list_strategies(StrategyType.PULLBACK),
            "entry": StrategyRegistry.list_strategies(StrategyType.ENTRY),
        }
